import { describe,it,expect } from "vitest";
import request from "supertest";
import { app } from "../../app";
let n=0; const unico=()=>`${Date.now()}.${n++}`;
async function criarParte(nome=`Parte ${unico()}`){const x=await request(app).post("/v1/partes").send({tipo:"organizacao",nome_exibicao:nome,organizacao:{nome_fantasia:nome}}).expect(201);return x.body.id as string;}
async function contexto(){const marca=await criarParte();const cli=await request(app).post("/v1/clientes").send({parte_id:marca}).expect(201);const pro=await request(app).post("/v1/projetos").send({cliente_cross_id:cli.body.id,nome:"Projeto",objetivo:"Resultados"}).expect(201);const fre=await request(app).post(`/v1/projetos/${pro.body.id}/frentes`).send({nome:"Frente",objetivo:"Objetivo"}).expect(201);const par=await criarParte();const can=await request(app).post(`/v1/frentes/${fre.body.id}/candidaturas`).send({parte_id:par}).expect(201);const pap=await request(app).post(`/v1/frentes/${fre.body.id}/papers`).send({titulo:"Paper"}).expect(201);const ver=await request(app).post(`/v1/papers/${pap.body.id}/versoes`).send({estrategia_proposta:"Co-branding"}).expect(201);await request(app).post(`/v1/versoes-paper/${ver.body.id}/validacoes`).send({tipo_validacao_codigo:"cliente",status_validacao_codigo:"aprovada"}).expect(201);await request(app).post(`/v1/candidaturas/${can.body.id}/decisoes`).send({tipo_decisao_codigo:"aprovada"}).expect(201);const p=await request(app).post(`/v1/candidaturas/${can.body.id}/parceria`).send({tipo_parceria_codigo:"co_branding"}).expect(201);return {parceriaId:p.body.id as string,projetoId:pro.body.id as string};}

describe("Resultados e acompanhamento (RF043–RF047)",()=>{
 it("registra e lista acompanhamento",async()=>{const {parceriaId}=await contexto();await request(app).post(`/v1/parcerias/${parceriaId}/acompanhamentos`).send({descricao:"Reunião mensal"}).expect(201);const x=await request(app).get(`/v1/parcerias/${parceriaId}/acompanhamentos`).expect(200);expect(x.body.itens).toHaveLength(1);});
 it("cria, vincula, mede e desvincula indicador",async()=>{const {parceriaId}=await contexto();const i=await request(app).post("/v1/indicadores").send({nome:`Alcance ${unico()}`,tipo_metrica_codigo:"alcance",unidade:"pessoas"});expect(i.status).toBe(201);expect((await request(app).get("/v1/indicadores").expect(200)).body.itens.some((x:{id:string})=>x.id===i.body.id)).toBe(true);await request(app).post(`/v1/parcerias/${parceriaId}/indicadores`).send({indicador_id:i.body.id,meta:1000}).expect(201);expect((await request(app).get(`/v1/parcerias/${parceriaId}/indicadores`).expect(200)).body.itens).toHaveLength(1);const m=await request(app).post(`/v1/parcerias/${parceriaId}/medicoes`).send({indicador_id:i.body.id,periodo_inicio:"2026-07-01",periodo_fim:"2026-07-31",valor:1250});expect(m.status).toBe(201);expect((await request(app).get(`/v1/parcerias/${parceriaId}/medicoes`).expect(200)).body.itens).toHaveLength(1);await request(app).delete(`/v1/parcerias/${parceriaId}/indicadores/${i.body.id}`).expect(204);});
 it("rejeita medição com período invertido",async()=>{const {parceriaId}=await contexto();const x=await request(app).post(`/v1/parcerias/${parceriaId}/medicoes`).send({indicador_id:"00000000-0000-0000-0000-000000000000",periodo_inicio:"2026-08-01",periodo_fim:"2026-07-01",valor:1});expect(x.status).toBe(422);});
 it("registra resultado e exige moeda quando há valor",async()=>{const {parceriaId}=await contexto();expect((await request(app).post(`/v1/parcerias/${parceriaId}/resultados`).send({descricao:"Receita",valor:100})).status).toBe(422);await request(app).post(`/v1/parcerias/${parceriaId}/resultados`).send({descricao:"Receita",valor:100,moeda:"BRL"}).expect(201);expect((await request(app).get(`/v1/parcerias/${parceriaId}/resultados`).expect(200)).body.itens).toHaveLength(1);});
 it("calcula ROI no servidor e mantém histórico independente",async()=>{const {parceriaId}=await contexto();const a=await request(app).post(`/v1/parcerias/${parceriaId}/calculos-roi`).send({investimento_estimado:100,retorno_estimado:150,moeda:"BRL"}).expect(201);expect(Number(a.body.roi)).toBe(.5);expect((await request(app).get(`/v1/calculos-roi/${a.body.id}`).expect(200)).body.id).toBe(a.body.id);const b=await request(app).post(`/v1/parcerias/${parceriaId}/calculos-roi`).send({investimento_estimado:100,retorno_estimado:300,moeda:"BRL",roi:999}).expect(201);expect(Number(b.body.roi)).toBe(2);expect(b.body.id).not.toBe(a.body.id);expect((await request(app).get(`/v1/parcerias/${parceriaId}/calculos-roi`).expect(200)).body.itens).toHaveLength(2);});
 it("prioriza valores realizados no ROI",async()=>{const {parceriaId}=await contexto();const x=await request(app).post(`/v1/parcerias/${parceriaId}/calculos-roi`).send({investimento_estimado:100,retorno_estimado:200,investimento_realizado:200,retorno_realizado:260,moeda:"BRL"}).expect(201);expect(Number(x.body.roi)).toBe(.3);});
 it("encerra projeto e parceria uma única vez (RN034)",async()=>{const {parceriaId,projetoId}=await contexto();await request(app).post(`/v1/projetos/${projetoId}/encerramento`).send({motivo:"Concluído"}).expect(201);await request(app).get(`/v1/projetos/${projetoId}/encerramento`).expect(200);expect((await request(app).post(`/v1/projetos/${projetoId}/encerramento`).send({motivo:"Novo"})).status).toBe(409);await request(app).post(`/v1/parcerias/${parceriaId}/encerramento`).send({motivo:"Concluída"}).expect(201);await request(app).get(`/v1/parcerias/${parceriaId}/encerramento`).expect(200);});
 it("retorna 404 para pais inexistentes",async()=>{await request(app).get("/v1/parcerias/00000000-0000-0000-0000-000000000000/resultados").expect(404);await request(app).get("/v1/projetos/00000000-0000-0000-0000-000000000000/encerramento").expect(404);});
});
