import { PoolClient } from "pg";
import type { CalcularRoiInput, CriarAcompanhamentoInput, CriarIndicadorInput, EncerrarParceriaInput, EncerrarProjetoInput, RegistrarMedicaoInput, RegistrarResultadoInput, VincularIndicadorInput } from "./resultados.schema";

export async function existeParceria(c: PoolClient, id: string) { const r = await c.query("SELECT 1 FROM cross_partnerships.parceria WHERE id=$1 AND arquivado_em IS NULL", [id]); return r.rowCount !== 0; }
export async function existeProjeto(c: PoolClient, id: string) { const r = await c.query("SELECT 1 FROM cross_projects.projeto WHERE id=$1 AND arquivado_em IS NULL", [id]); return r.rowCount !== 0; }
export async function existeIndicador(c: PoolClient, id: string) { const r = await c.query("SELECT 1 FROM cross_analytics.indicador WHERE id=$1 AND ativo", [id]); return r.rowCount !== 0; }
export async function resolverTipoMetrica(c: PoolClient, codigo: string) { const { rows } = await c.query("SELECT id FROM cross_analytics.tipo_metrica WHERE codigo=$1", [codigo]); return rows[0]?.id as string | undefined; }

export async function inserirAcompanhamento(c: PoolClient, parceriaId: string, i: CriarAcompanhamentoInput, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.acompanhamento (parceria_id,descricao,data_registro,criado_por_id) VALUES ($1,$2,COALESCE($3::timestamptz,NOW()),$4) RETURNING *`, [parceriaId,i.descricao,i.data_registro ?? null,usuarioId]); return rows[0]; }
export async function listarAcompanhamentos(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.acompanhamento WHERE parceria_id=$1 ORDER BY data_registro DESC", [id]); return rows; }

export async function inserirIndicador(c: PoolClient, i: CriarIndicadorInput, tipoId: string) { const { rows } = await c.query(`INSERT INTO cross_analytics.indicador (nome,tipo_metrica_id,unidade,descricao) VALUES ($1,$2,$3,$4) RETURNING id,nome,unidade,descricao,ativo`, [i.nome,tipoId,i.unidade ?? null,i.descricao ?? null]); return { ...rows[0], tipo_metrica: i.tipo_metrica_codigo }; }
export async function listarIndicadores(c: PoolClient) { const { rows } = await c.query(`SELECT i.id,i.nome,t.codigo AS tipo_metrica,i.unidade,i.descricao,i.ativo FROM cross_analytics.indicador i JOIN cross_analytics.tipo_metrica t ON t.id=i.tipo_metrica_id WHERE i.ativo ORDER BY i.nome`); return rows; }
export async function vincularIndicador(c: PoolClient, parceriaId: string, i: VincularIndicadorInput) { const { rows } = await c.query(`INSERT INTO cross_analytics.parceria_indicador (parceria_id,indicador_id,meta) VALUES ($1,$2,$3) RETURNING parceria_id,indicador_id,meta`, [parceriaId,i.indicador_id,i.meta ?? null]); return rows[0]; }
export async function listarIndicadoresParceria(c: PoolClient, id: string) { const { rows } = await c.query(`SELECT i.id AS indicador_id,i.nome,t.codigo AS tipo_metrica,i.unidade,pi.meta FROM cross_analytics.parceria_indicador pi JOIN cross_analytics.indicador i ON i.id=pi.indicador_id JOIN cross_analytics.tipo_metrica t ON t.id=i.tipo_metrica_id WHERE pi.parceria_id=$1 ORDER BY i.nome`, [id]); return rows; }
export async function desvincularIndicador(c: PoolClient, parceriaId: string, indicadorId: string) { const r = await c.query("DELETE FROM cross_analytics.parceria_indicador WHERE parceria_id=$1 AND indicador_id=$2", [parceriaId,indicadorId]); return r.rowCount ?? 0; }

export async function inserirMedicao(c: PoolClient, parceriaId: string, i: RegistrarMedicaoInput, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.medicao_indicador (parceria_id,indicador_id,periodo_inicio,periodo_fim,valor,unidade,fonte,nivel_confianca,criado_por_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [parceriaId,i.indicador_id,i.periodo_inicio,i.periodo_fim,i.valor,i.unidade ?? null,i.fonte ?? null,i.nivel_confianca ?? null,usuarioId]); return rows[0]; }
export async function listarMedicoes(c: PoolClient, id: string) { const { rows } = await c.query(`SELECT m.*,i.nome AS indicador_nome FROM cross_analytics.medicao_indicador m JOIN cross_analytics.indicador i ON i.id=m.indicador_id WHERE m.parceria_id=$1 ORDER BY m.periodo_fim DESC,m.criado_em DESC`, [id]); return rows; }
export async function inserirResultado(c: PoolClient, parceriaId: string, i: RegistrarResultadoInput, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.resultado (parceria_id,descricao,valor,moeda,alcance_realizado,criado_por_id) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [parceriaId,i.descricao,i.valor ?? null,i.moeda ?? null,i.alcance_realizado ?? null,usuarioId]); return rows[0]; }
export async function listarResultados(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.resultado WHERE parceria_id=$1 ORDER BY data_registro DESC", [id]); return rows; }

export async function inserirRoi(c: PoolClient, parceriaId: string, i: CalcularRoiInput, roi: number | null, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.calculo_roi (parceria_id,investimento_estimado,investimento_realizado,retorno_estimado,retorno_realizado,moeda,roi,premissas,nivel_confianca,criado_por_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`, [parceriaId,i.investimento_estimado ?? null,i.investimento_realizado ?? null,i.retorno_estimado ?? null,i.retorno_realizado ?? null,i.moeda,roi,i.premissas ?? null,i.nivel_confianca ?? null,usuarioId]); return rows[0]; }
export async function listarRois(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.calculo_roi WHERE parceria_id=$1 ORDER BY data_calculo DESC", [id]); return rows; }
export async function buscarRoi(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.calculo_roi WHERE id=$1", [id]); return rows[0] ?? null; }

export async function encerrarProjeto(c: PoolClient, id: string, i: EncerrarProjetoInput, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.encerramento_projeto (projeto_id,motivo,resultados_gerais,aprendizados,proximos_passos,criado_por_id) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [id,i.motivo,i.resultados_gerais ?? null,i.aprendizados ?? null,i.proximos_passos ?? null,usuarioId]); return rows[0]; }
export async function buscarEncerramentoProjeto(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.encerramento_projeto WHERE projeto_id=$1", [id]); return rows[0] ?? null; }
export async function encerrarParceria(c: PoolClient, id: string, i: EncerrarParceriaInput, usuarioId: string | null) { const { rows } = await c.query(`INSERT INTO cross_analytics.encerramento_parceria (parceria_id,motivo,resultados,cumprimento_contrapartidas,indicadores_finais,aprendizados,criado_por_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`, [id,i.motivo,i.resultados ?? null,i.cumprimento_contrapartidas ?? null,i.indicadores_finais ?? null,i.aprendizados ?? null,usuarioId]); return rows[0]; }
export async function buscarEncerramentoParceria(c: PoolClient, id: string) { const { rows } = await c.query("SELECT * FROM cross_analytics.encerramento_parceria WHERE parceria_id=$1", [id]); return rows[0] ?? null; }
